In [116]:
import pandas as pd
import numpy as np

In [117]:
superdata = pd.read_csv('super_allinformation_20130106_20150106.csv', index_col='day', parse_dates=True)

In [122]:
superdata.head()

            number  return  trade  daily_return_volatility
day
2013-01-07    1101 -0.2564    0.0                 3.010530
2013-01-07    1102 -0.5376    0.0                -0.245908
2013-01-07    1201  3.2595    0.0                -1.348642
2013-01-08    1101 -1.0283    0.0                -1.126325
2013-01-08    1102 -0.4054    0.0                -1.334731

In [120]:
superdata['daily_return_volatility'] = 0

In [121]:
for i in range(len(superdata.index)-3):
    if(superdata['return'].iloc[i]==0):
        superdata['daily_return_volatility'].iloc[i] = 0
    else:
        superdata['daily_return_volatility'].iloc[i] = (superdata['return'].iloc[i+3] - superdata['return'].iloc[i])/superdata['return'].iloc[i]

C:\Users\pluser\Anaconda3\lib\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [110]:
superdata = superdata.dropna() # drop null value

In [123]:
superdata

            number  return  trade  daily_return_volatility
day
2013-01-07    1101 -0.2564   0.00                 3.010530
2013-01-07    1102 -0.5376   0.00                -0.245908
2013-01-07    1201  3.2595   0.00                -1.348642
2013-01-08    1101 -1.0283   0.00                -1.126325
2013-01-08    1102 -0.4054   0.00                -1.334731
2013-01-08    1201 -1.1364   0.00                -1.786695
2013-01-09    1101  0.1299   0.00                20.966128
2013-01-09    1102  0.1357   0.00                14.976419
2013-01-09    1201  0.8940   0.00                -1.000000
2013-01-10    1101  2.8534   0.00                -1.000000
2013-01-10    1102  2.1680   0.00                -1.122371
2013-01-10    1201  0.0000   0.00                 0.000000
2013-01-11    1101  0.0000   0.00                 0.000000
2013-01-11    1102 -0.2653   0.00                -1.000000
2013-01-11    1201  3.1646   0.00                -0.418410
2013-01-14    1101 -0.3783   0.00                 2.346022
2013-01-14    1102  0.0000   0.00                 0.000000
2013-01-14    1201  1.8405   0.00                -0.934529
2013-01-15    1101 -1.2658   0.00                -0.898720
2013-01-15    1102 -1.0638   0.00                -0.241869
2013-01-15    1201  0.1205   0.00                 4.991701
2013-01-16    1101 -0.1282   0.00                22.030421
2013-01-16    1102 -0.8065   0.00                 1.352139
2013-01-16    1201  0.7220   0.00                -2.158310
2013-01-17    1101 -2.9525   0.00                -1.851211
2013-01-17    1102 -1.8970   0.00                -1.509700
2013-01-17    1201 -0.8363   0.00                -0.423771
2013-01-18    1101  2.5132   0.00                -0.897302
2013-01-18    1102  0.9669   0.00                -1.707415
2013-01-18    1201 -0.4819   0.00                -2.004980
...            ...     ...    ...                      ...
2014-12-23    1101  1.0601   1.41                -0.890010
2014-12-23    1102  0.0000   1.65                 0.000000
2014-12-23    1201  1.4374   0.00                -1.563309
2014-12-24    1101  0.1166   1.07                 2.993997
2014-12-24    1102  1.0568   2.22                -0.752650
2014-12-24    1201 -0.8097   0.00                -1.504137
2014-12-25    1101  0.4657   1.33                -1.746403
2014-12-25    1102  0.2614   0.43                 0.496174
2014-12-25    1201  0.4082   0.00                 1.987506
2014-12-26    1101 -0.3476   0.66                -0.665420
2014-12-26    1102  0.3911   0.22                -0.335975
2014-12-26    1201  1.2195   0.00                -0.670685
2014-12-27    1101 -0.1163   0.24               -10.008598
2014-12-27    1102  0.2597   1.51                -0.501348
2014-12-27    1201  0.4016   0.00                -2.992032
2014-12-29    1101  1.0477   3.15                -0.670135
2014-12-29    1102  0.1295   4.71                -0.000772
2014-12-29    1201 -0.8000   0.00                -2.008125
2014-12-30    1101  0.3456   2.53                -1.996528
2014-12-30    1102  0.1294   1.91                 4.990726
2014-12-30    1201  0.8065   0.00                -1.000000
2014-12-31    1101 -0.3444   8.44                 1.676249
2014-12-31    1102  0.7752   2.95                -3.480779
2014-12-31    1201  0.0000   0.00                 0.000000
2015-01-05    1101 -0.9217   4.40                 0.892373
2015-01-05    1102 -1.9231   1.25                -0.116375
2015-01-05    1201  0.0000   0.00                 0.000000
2015-01-06    1101 -1.7442   0.84                 0.000000
2015-01-06    1102 -1.6993   7.16                 0.000000
2015-01-06    1201 -0.6000   0.00                 0.000000

[1479 rows x 4 columns]

In [134]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
xfit = superdata['trade']
yfit = superdata['daily_return_volatility']

In [137]:
xfit = np.array(xfit).reshape(-1,1)

In [139]:
lin_reg.fit(xfit,yfit)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [144]:
lin_reg.coef_

array([-0.02518015])

In [145]:
lin_reg.intercept_

-0.861853429963093